version: '3.8'

services:
  db:
    image: mariadb
#    platform: linux/x86_64
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend-network
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  dev:
    depends_on:
      - db
    container_name: api_dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn run start:dev
    ports:
      - "4000:4000"
    networks:
      - backend-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  prod:
    depends_on:
      - db
    container_name: api_prod
#    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: yarn run start:prod
    ports:
      - "4000:4000"
    networks:
      - backend-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  backend-network:

volumes:
  dbdata:
