export const PARTIES_REPOSITORY = 'PARTIES_REPOSITORY';
export const MEMBERS_REPOSITORY = 'MEMBERS_REPOSITORY';
export const USERS_REPOSITORY = 'USER_REPOSITORY';
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
